import "./globals.css"
import type { Metadata } from "next"
import { DisableDraftModeTrigger } from "@/components/disable-draft-mode-trigger"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className="bg-dark-blue-600 isolate flex min-h-screen flex-col overflow-x-hidden">
        {children}
      </div>
      <DisableDraftModeTrigger />
    </>
  )
}
