import { cn } from "@/lib/utils"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Script from "next/script"
import { Footer } from "@/components/footer"
import { GoogleAnalytics } from "@next/third-parties/google"
import { FacebookPixel } from "@/components/facebook-pixel"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn("scroll-smooth", inter.variable)}>
      <body>
        {children}
        <Footer />
      </body>

      <Script src="https://app.iclosed.io/assets/widget.js" />
      <GoogleAnalytics gaId="AW-1017877798" />
      <FacebookPixel />
    </html>
  )
}
