import { cn } from "@/lib/utils"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Script from "next/script"
import Link from "next/link"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Marketeq = ({ className, ...props }: React.SVGProps<SVGSVGElement>) => {
  return (
    <svg
      className={cn("h-[22px] w-[150px]", className)}
      viewBox="0 0 150 22"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path
        d="M33.826 21.968c-1.4 0-2.636-.731-3.994-1.624a5.16 5.16 0 0 0-5.603-.049C22.854 21.107 21.496 22 19.903 22h-.501a4.94 4.94 0 0 1-3.21-1.226 4.97 4.97 0 0 1-1.641-3.028l-.025-.699c.012-.853.234-1.69.647-2.435l1.94-3.41 1.213 2.135-1.374 2.338a2.81 2.81 0 0 0 1.04 3.8c.421.244.9.372 1.386.373h.573c2.078-.04 3.412-2.435 7.043-2.435 3.492 0 4.85 2.476 6.791 2.476a2.42 2.42 0 0 0 2.157-1.185 2.44 2.44 0 0 0 .018-2.469L28.756 3.53a2.81 2.81 0 0 0-2.425-1.401 2.8 2.8 0 0 0-2.426 1.401l-2.91 5.042-1.213-2.127 2.247-3.962a4.9 4.9 0 0 1 1.8-1.817 4.9 4.9 0 0 1 6.73 1.817l7.204 12.674a4.57 4.57 0 0 1-.017 4.543 4.55 4.55 0 0 1-1.658 1.66 4.5 4.5 0 0 1-2.262.608"
        fill="#306cfe"
      />
      <path
        opacity={0.5}
        d="M23.462 15.573c-.138-.325-7.35-12.99-7.398-13.064a4.9 4.9 0 0 0-1.8-1.816 4.9 4.9 0 0 0-6.73 1.816L.62 14.615a4.93 4.93 0 0 0 .05 4.877 4.9 4.9 0 0 0 1.784 1.777 4.9 4.9 0 0 0 2.427.653h.51c1.616 0 2.95-.885 4.325-1.705a5.27 5.27 0 0 1 4.042-.593 6.3 6.3 0 0 1-.566-2.257 7.43 7.43 0 0 0-4.495.982c-6.169 3.589-7.277-.876-6.274-2.72L9.329 3.451a2.81 2.81 0 0 1 2.425-1.402 2.8 2.8 0 0 1 2.426 1.402l4.85 8.5.745 1.316c1.447 2.582 1.94 3.183 1.94 3.938q.042.26 0 .52a12.4 12.4 0 0 1 2.086-1.105 4.5 4.5 0 0 0-.34-1.047"
        fill="#306cfe"
      />
      <path
        d="M70.75 9.037a.572.572 0 0 1 .364-.773 14 14 0 0 1 1.822-.373q1.401-.22 2.932-.22 1.326 0 2.218.26.892.241 1.402.703.536.461.74 1.104.23.642.229 1.445 0 .882-.076 1.786-.076.882-.102 1.746 0 .863.076 1.686.031.337.105.66c.095.421-.2.865-.631.865h-1.381a.6.6 0 0 1-.562-.385l-.36-.93a.11.11 0 0 0-.187-.03q-.507.597-1.395 1.044-.892.441-2.32.441-.892 0-1.606-.2a4 4 0 0 1-1.224-.603 2.95 2.95 0 0 1-.79-.923 2.6 2.6 0 0 1-.28-1.204q0-.923.509-1.545.535-.643 1.504-1.024.994-.4 2.346-.542 1.377-.16 3.06-.1.177-1.124-.204-1.605-.383-.502-1.709-.502-.994 0-2.116.16-.708.104-1.255.25a.65.65 0 0 1-.774-.367zm3.97 6.882q.995 0 1.581-.341.587-.361.867-.763v-1.304a12 12 0 0 0-1.53-.02q-.713.039-1.275.18-.56.141-.892.402a.81.81 0 0 0-.331.662q0 .562.407.883.434.3 1.173.3m15.671-6.252c-.062.35-.412.566-.762.505a4.6 4.6 0 0 0-.781-.072q-.893 0-1.505.381-.538.33-.753.848a.5.5 0 0 0-.037.198v5.778c0 .332-.27.602-.602.602h-2.11a.6.6 0 0 1-.602-.602v-8.83c0-.333.27-.603.602-.603h1.52c.268 0 .504.178.578.435l.257.89c.29-.495.782-.877 1.275-1.144q.739-.402 1.734-.402.441 0 .963.099a.57.57 0 0 1 .444.669zm6.174 4.327a.6.6 0 0 0-.482-.242h-.591v3.553c0 .332-.27.602-.602.602h-2.11a.6.6 0 0 1-.603-.602V5.434c0-.256.163-.484.405-.568l2.11-.732c.392-.135.8.155.8.57v7.442c.498-.183.931-.51 1.244-.94l2.29-3.148a.46.46 0 0 1 .369-.187h2.159c.505 0 .786.585.47.979l-2.886 3.597.713.783 2.737 3.717a.602.602 0 0 1-.485.959h-2.307a.6.6 0 0 1-.482-.242zm17.707 2.539c.181.281.098.658-.206.799q-.645.3-1.556.535-1.3.32-2.779.32-3.085 0-4.513-1.404-1.428-1.425-1.427-3.894 0-2.649 1.606-3.973 1.606-1.325 4.513-1.325a8.8 8.8 0 0 1 1.886.2 4.9 4.9 0 0 1 1.632.663 3.4 3.4 0 0 1 1.147 1.244q.434.783.434 1.947 0 .422-.077.903c-.063.596-.599 1.004-1.198 1.004h-6.629q.076 1.264.816 1.906.765.642 2.448.642 1.044 0 1.861-.24.427-.133.75-.266c.301-.124.665-.038.841.236zm-4.413-6.855q-1.3 0-1.938.623-.612.601-.739 1.625h4.194c.31 0 .579-.238.557-.547q-.051-.693-.443-1.119-.51-.582-1.631-.582m6.165-1.204c0-.332.27-.602.602-.602h1.157V6.423c0-.261.169-.493.417-.573l2.111-.682a.602.602 0 0 1 .787.573v2.13h2.508c.333 0 .602.27.602.602v1.004a.6.6 0 0 1-.602.602h-2.508v3.853q0 1.043.255 1.505.28.442 1.02.442a4 4 0 0 0 1.101-.136c.334-.085.688.092.785.423l.252.864a.57.57 0 0 1-.371.712 12 12 0 0 1-1.079.264q-.918.18-1.861.18-1.76 0-2.601-.702-.816-.723-.816-2.348V10.08h-1.157a.6.6 0 0 1-.602-.602zm19.96 8.059c.181.281.098.658-.206.799q-.645.3-1.556.535-1.3.32-2.779.32-3.085 0-4.513-1.404-1.428-1.425-1.428-3.894 0-2.649 1.606-3.973 1.607-1.325 4.513-1.325a8.8 8.8 0 0 1 1.887.2 4.9 4.9 0 0 1 1.632.663 3.4 3.4 0 0 1 1.147 1.244q.434.783.434 1.947 0 .422-.077.903c-.063.596-.6 1.004-1.198 1.004h-6.629q.077 1.264.816 1.906.764.642 2.447.642 1.046 0 1.861-.24a9 9 0 0 0 .751-.266c.301-.124.664-.038.84.236zm-4.414-6.855q-1.3 0-1.937.623-.612.601-.74 1.625h4.194c.311 0 .58-.238.557-.547q-.05-.693-.442-1.119-.51-.582-1.632-.582m18.152 10.809a.6.6 0 0 1-.431.577l-2.11.627a.602.602 0 0 1-.774-.578v-4.07c-.289.348-.782.63-1.274.844q-.74.3-1.913.3-2.37.001-3.646-1.264-1.25-1.264-1.249-3.833 0-2.689 1.708-4.074 1.734-1.385 4.947-1.385.687 0 1.376.06.689.04 1.301.141.638.08 1.173.2.243.047.449.092a.57.57 0 0 1 .443.566zm-5.609-4.507q.97 0 1.478-.341.492-.314.769-.915a.54.54 0 0 0 .047-.228V10.1a2.8 2.8 0 0 0-.867-.2 9 9 0 0 0-1.096-.061q-1.352 0-2.04.803-.662.803-.662 2.348 0 1.465.611 2.227.612.763 1.76.763M64.168 8.816l-4.535 6.252a.6.6 0 0 1-.487.249h-.513a.6.6 0 0 1-.482-.242L53.595 8.98l-.006 8.324c0 .332-.27.602-.602.602h-2.11a.6.6 0 0 1-.603-.602V4.459c0-.332.27-.602.602-.602h2.287c.188 0 .365.088.48.238l5.397 7.094a.1.1 0 0 0 .163-.003L64.27 4.11a.6.6 0 0 1 .49-.252h2.25c.332 0 .602.27.602.602v12.845c0 .332-.27.602-.602.602h-2.286a.6.6 0 0 1-.602-.606z"
        fill="#22376b"
      />
    </svg>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn("scroll-smooth", inter.variable)}>
      <body>
        {children}
        <footer className="5xl:px-[300px] 4xl:px-[150px] p-5 md:p-10 lg:px-[100px] lg:py-[50px]">
          <div className="3xl:flex 3xl:items-center 3xl:justify-between grid">
            <div className="3xl:gap-x-[50px] 3xl:justify-start flex items-center justify-between">
              <Link href="/" className="focus-visible:outline-none">
                <Marketeq className="3xl:w-[149.72px] 3xl:h-[22px] h-[18.95px] w-[129px]" />
              </Link>

              <span className="text-dark-blue-400 3xl:text-sm 3xl:leading-none inline-block text-center text-xs leading-[1.8] md:text-left">
                © 2011 - 2025 Marketeq Digital Inc. All Rights Reserved.
              </span>
            </div>

            <div className="3xl:flex hidden items-center gap-x-5">
              <Link
                href="/terms-of-use"
                className="text-dark-blue-400 decoration-dark-blue-400/50 hover:decoration-dark-blue-400 cursor-pointer text-[10px] font-semibold underline transition duration-300 focus-visible:outline-none md:text-sm"
              >
                Terms of Use
              </Link>
              <Link
                href="/privacy-policy"
                className="text-dark-blue-400 decoration-dark-blue-400/50 hover:decoration-dark-blue-400 cursor-pointer text-[10px] font-semibold underline transition duration-300 focus-visible:outline-none md:text-sm"
              >
                Privacy Policy
              </Link>
            </div>
          </div>

          <div className="3xl:mt-[50px] mt-5">
            <span className="text-dark-blue-400 3xl:text-sm inline-block text-center text-xs leading-none">
              This site is not a part of Google™ or Meta™, including
              Facebook™ and Instagram™. It is not endorsed by Google™,
              Meta™, Facebook™, or Instagram™ in any way. All trademarks and
              brand names mentioned are the property of their respective owners.
            </span>
          </div>

          <div className="mt-5">
            <span className="text-dark-blue-400 3xl:text-sm inline-block text-center text-xs leading-none">
              DISCLAIMER: The results and performance metrics shared on this
              page and during our consultations represent the outcomes of our
              work and, in some cases, those of previous or current clients.
              Please understand that these results are not typical, and we are
              not implying that you will achieve the same results (or any
              results at all). The examples provided are for illustration
              purposes only. Your results may vary based on numerous factors,
              including but not limited to your business model, market
              conditions, background, experience, and dedication. All business
              initiatives involve risk, along with significant and consistent
              effort. If you are not ready to accept this, please DO NOT ENGAGE
              WITH MARKETEQ&apos;S SERVICES. Marketeq Digital is committed to
              delivering high-quality work in all our projects. However, we do
              not offer any performance, results, or outcome guarantees.
              Outcomes can vary widely and depend on numerous factors beyond our
              control, so no specific return on investment or success is
              promised.
            </span>
          </div>

          <div className="3xl:hidden mt-5 flex items-center justify-center gap-x-5">
            <Link
              href="/terms-of-use"
              className="text-dark-blue-400 decoration-dark-blue-400/50 hover:decoration-dark-blue-400 cursor-pointer text-[10px] font-semibold underline transition duration-300 focus-visible:outline-none md:text-sm"
            >
              Terms of Use
            </Link>
            <Link
              href="/privacy-policy"
              className="text-dark-blue-400 decoration-dark-blue-400/50 hover:decoration-dark-blue-400 cursor-pointer text-[10px] font-semibold underline transition duration-300 focus-visible:outline-none md:text-sm"
            >
              Privacy Policy
            </Link>
          </div>
        </footer>
      </body>

      <Script
        src="https://app.iclosed.io/assets/widget.js"
        strategy="afterInteractive"
      />
    </html>
  )
}
